return {
  ensure_installed = {
    "lua-language-server",
    "rust-analyzer",
    "rustfmt",
    "stylua",
    "sql-formatter",
    "dockerfile-language-server",
    "docker-compose-language-service",
    "buf-language-server",
    "prettierd",
    "typescript-language-server",
    "clangd",
    "clang-format",
    "codelldb",
    "jdtls",
    "java-debug-adapter",
  },
  max_concurrent_installers = 10,
}
